# Generated by Django 5.2.8 on 2025-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اسلاید')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'مدیریت اسلایدر',
                'ordering': ('-created',),
            },
        ),
    ]
