# Generated by Django 5.2.8 on 2025-11-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, help_text='متنی که ربات سایت وقتی کاربر درباره این محصول پرسید، نمایش می\u200cدهد.', verbose_name='توضیحات برای هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ مدیر سایت'),
        ),
    ]
