# Generated by Django 5.2.8 on 2025-11-25 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_ai_description_review_admin_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ قابل پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, help_text='متنی که ربات سایت می\u200cخواند.', verbose_name='توضیحات برای هوش مصنوعی'),
        ),
    ]
