# Generated by Django 5.2.8 on 2025-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_coupon_order_discount_amount_order_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product', verbose_name='محصولات مجاز (خالی = همه)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, verbose_name='توضیحات برای هوش مصنوعی'),
        ),
    ]
